[template]
src="leo_gateway.tmpl"
dest="/opt/leofs/leo_gateway/etc/leo_gateway.conf"
owner="root"
mode="644"
keys= [
  "CONF_GATEWAY_NAME",
  "CONF_GATEWAY_IP",
  "CONF_GATEWAY_PROTOCOL",
  "CONF_GATEWAY_HTTP_PORT",
  "CONF_GATEWAT_NFS_MOUNTD_PORT",
  "CONF_GATEWAT_NFS_NFSD_PORT",
  "CONF_GATEWAY_CHUNCKED_OBJ_LEN",
  "CONF_LOG_LEVEL",
  "CONF_DISTRIBUTED_COOKIE",
  "CONF_MANAGER_MASTER_IP",
  "CONF_MANAGER_SLAVE_IP",
]
